## "What is Human Development?" & "The Best Stats You’ve Never Seen"

What are some of the targeted issues that Jahan examples as requiring focus throughout the world? Elaborate further on Jahan’s definition of human development. What are the different measures incorporated into the Human Development Index that serve to capture the breadth and focus of each countries’ average achievement?

In the podcast, Jahan describes human development as "the enlargement of human choices." He states that human development should enlarge choices in every aspect of life; there are two sides the capabilities of people need to be enhanced and the opportunities of human beings need to be enhanced to use the capabilities. The two sides of Jahan's definitions mean that human development is more than a one-sided problem. Human development requires the understanding that for choices to be enhanced, persons have to be empowered to use the tools they are being provided; i.e. populations cannot go from having nothing to something without the education to put systems in to place that continue the growth and development of their countries. It's like the classic saying "Give a man a fish, and you feed him for a day. Teach a man to fish and you will feed him for a lifetime." Jahan also talks about how development of the people, for the people, by the people; meaning human capital is cultivated for helping others and people are not only receiving but are active in the development. 
"The Human Development Index a summary measure of average achievement in key dimensions of human development: a long and healthy life, being knowledgeable and have a decent standard of living." ([United Nations HDR] (http://hdr.undp.org/en/content/human-development-index-hdi)) In the HDI there are two measures: Breadth and Focus. The Breadth measure is more comprehensive in detail and covers statistics such as mortality rates, unemployment, etc. The Focus measure covers the details that make up the front of the HDI; life expectance, knowledge, and standards of living. Jahan used a metaphor to describe the two; the Breadth is a house, and Focus is the door, he said “don’t mistake the door for the house, and don’t stop at the door.” Meaning the focus is just and entrance to the HDI and the Breadth is the larger idea. He also touched on how the HDI is a measure of Human development, it does not cover the totality of development.

What were some of the examples Rosling presented where health appeared to be a precursor to wealth? What was Rosling’s warning regarding the dangers of using averages when describing development?

Rosling stated that countries are moving at the same rate as money and health. He mentions that countries can move faster if they are healthier, to show this he uses the United Arab Emirates as an example. The UAE started selling oil and go the money, but Rosling explains that health cannot be bought, it is an investment in a support system to provide health to a country. That is how the UAE became “mainstream” as Rosling describes it. 
Rosling ‘s warning of averages goes along the lines of an average skews the data to represent something in the middle, but when the scale of the data is split into subdivisions it reveals that most solutions being proposed already exist. By dividing Africa by income levels Rosling showed that universal plans miss their intended targets because a blanket solution doesn’t solve the disparity that exists in Africa.
